# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - ./apps/web/.env
    environment:
      - DATABASE_URL=prisma+postgres://postgres:password@db:5432/myapp
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - db
    volumes:
      - .:/the-pigeon-post
      - /the-pigeon-post/node_modules
    command: npm run dev  # change to npm start for production

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
